#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 -U ${POSTGRES_USER} -d ${POSTGRES_DB} <<-EOSQL
    CREATE DATABASE ${DB_NAME};
    CREATE ROLE ${DB_USER} WITH LOGIN PASSWORD '${DB_PASSWORD}';
    
    \c ${DB_NAME}
    
    REVOKE CREATE ON SCHEMA public FROM PUBLIC;
    CREATE SCHEMA IF NOT EXISTS ${DB_SCHEMA};
    GRANT USAGE, CREATE ON SCHEMA ${DB_SCHEMA} TO ${DB_USER};
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA}
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_USER};
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA}
    GRANT USAGE ON SEQUENCES TO ${DB_USER};
    
    GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL
